# -*- coding: utf-8 -*-
"""Dashboard Streamlit_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xmIWuWWYakg933HFbAHwkmVd1QzLMxr
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from datetime import time

st.set_page_config(
    page_title="Solar Power Forecasting Dashboard",
    layout="wide"
)

st.markdown(
    "<h1 style='text-align: center;'>☀️ Solar Power Forecasting & DSM Performance Dashboard</h1>",
    unsafe_allow_html=True
)

DATA_PATH = "dashboard_predictions.csv"

@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH)

    df["valid_time_ist"] = pd.to_datetime(df["valid_time_ist"])

    df = df.rename(columns={
        "avg_ghi": "GFS_GHI",
        "ALLSKY_SFC_SW_DWN": "Actual_GHI",
        "GHI_corrected": "Predicted_GHI"
    })

    df = df.sort_values("valid_time_ist").reset_index(drop=True)
    return df

df = load_data()

st.subheader("🏭 Plant Configuration")

c1, c2, c3, c4 = st.columns(4)

with c1:
    st.text_input("Country", value="India", disabled=True)

with c2:
    st.text_input("State", value="Karnataka", disabled=True)

with c3:
    st.text_input("Plant Type", value="Solar", disabled=True)

with c4:
    st.text_input("Plant Name", value="Pavagada Solar Plant", disabled=True)

st.subheader("📅 Forecast Selection")

available_dates = sorted(df["valid_time_ist"].dt.date.unique())

col_date, col_time = st.columns(2)

with col_date:
    selected_date = st.date_input(
        "Select Date",
        value=available_dates[-1],
        min_value=available_dates[0],
        max_value=available_dates[-1]
    )

with col_time:
    time_options = pd.date_range("06:30", "17:30", freq="1h").time
    
    selected_time = st.selectbox(
        "Select Time",
        options=time_options,
        format_func=lambda t: t.strftime("%I:%M %p")
    )


day_df = df[df["valid_time_ist"].dt.date == selected_date].copy()

day_df["hour"] = (
    day_df["valid_time_ist"].dt.hour +
    day_df["valid_time_ist"].dt.minute / 60
)

day_df = day_df[
    (day_df["hour"] >= 6.5) &
    (day_df["hour"] <= 17.5)
].copy()

if day_df.empty:
    st.warning("No data available for the selected date.")

else:
    st.success(f"Prediction available for {selected_date}")

    left_col, right_col = st.columns(2)

    with left_col:
        fig1 = go.Figure()

        fig1.add_trace(go.Scatter(
            x=day_df["valid_time_ist"],
            y=day_df["Predicted_GHI"],
            mode="lines+markers",
            name="Predicted GHI",
            line=dict(color="red"),
            marker=dict(color="red")
        ))

        fig1.update_layout(
            title="Predicted GHI",
            xaxis_title="Time",
            yaxis_title="GHI",
            height=450
        )

        st.plotly_chart(fig1, use_container_width=True)

    with right_col:
        fig2 = go.Figure()

        fig2.add_trace(go.Scatter(
            x=day_df["valid_time_ist"],
            y=day_df["Actual_GHI"],
            mode="lines+markers",
            name="Actual GHI"
        ))

        fig2.add_trace(go.Scatter(
            x=day_df["valid_time_ist"],
            y=day_df["GFS_GHI"],
            mode="lines+markers",
            name="GFS GHI"
        ))

        fig2.add_trace(go.Scatter(
            x=day_df["valid_time_ist"],
            y=day_df["Predicted_GHI"],
            mode="lines+markers",
            name="Predicted GHI"
        ))

        fig2.update_layout(
            title="Actual vs GFS vs Predicted GHI",
            xaxis_title="Time",
            yaxis_title="GHI",
            height=450
        )

        st.plotly_chart(fig2, use_container_width=True)
